 # SOLUCION DE SISTEMAS DE ECUACIONES LINEALES 


# Métodos Directos

In [750]:
import numpy as np
import scipy.linalg as scalg

In [751]:
A=np.array([[1.,1.,1.],[4.,3.,-1.],[3.,5.,3.]])
B=np.array([[1.],[6.],[4.]])

In [752]:
print(A)

[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]]


In [753]:
print(B)

[[1.]
 [6.]
 [4.]]


## Solución calculando la inversa

In [754]:
#calculo la inversa A
Ainv=np.linalg.inv(A)
print(Ainv)

[[ 1.40000000e+00  2.00000000e-01 -4.00000000e-01]
 [-1.50000000e+00  1.51394049e-17  5.00000000e-01]
 [ 1.10000000e+00 -2.00000000e-01 -1.00000000e-01]]


In [755]:
# alternativa solucion 1
x=np.matmul(Ainv,B)
print(x)

[[ 1. ]
 [ 0.5]
 [-0.5]]


In [756]:
# alternativa de solucion 2
x1=np.dot(Ainv,B)
print(x1)

[[ 1. ]
 [ 0.5]
 [-0.5]]


In [757]:
#alternativa de solucion 3
x2=np.linalg.solve(A,B)
print(x2)

[[ 1. ]
 [ 0.5]
 [-0.5]]


## Solución por Eliminación gaussiana

In [758]:
def ForwardElimination(A,b):
    n = len(b)
    for k in range(0,n-1):
        for i in range(k+1,n):
            f = A[i,k]/A[k,k]
            for j in range(k,n):
                A[i,j] = A[i,j] - f*A[k,j]
            b[i] = b[i] - f*b[k]
    return A,b

In [759]:
def BackwardSubstitution(A,b):
    n = len(b)
    x = np.zeros((n,1),'float')
    suma = 0.
    x[-1] = b[-1]/A[-1,-1]
    for i in range(n-2,-1,-1):
        suma = b[i]
        for j in range(i+1,n):
            suma = suma  - A[i,j]*x[j]
        x[i] = suma/A[i,i]
    return x

In [760]:
print(A)

[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]]


In [761]:
print(B)

[[1.]
 [6.]
 [4.]]


In [762]:
print(np.hstack((A,B)))

[[ 1.  1.  1.  1.]
 [ 4.  3. -1.  6.]
 [ 3.  5.  3.  4.]]


In [763]:
print(np.vstack((A,B.T)))

[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  6.  4.]]


In [764]:
A1,B1=ForwardElimination(A,B)
print(A1)

[[  1.   1.   1.]
 [  0.  -1.  -5.]
 [  0.   0. -10.]]


In [765]:
print(B1)

[[1.]
 [2.]
 [5.]]


In [766]:
BackwardSubstitution(A1,B1)

array([[ 1. ],
       [ 0.5],
       [-0.5]])

##  LU decomposition

In [767]:
A=np.array([[1.,1.,1.],[4.,3.,-1.],[3.,5.,3.]])
B=np.array([[1.],[6.],[4.]])
#alternativa de solucion 1
P,L,U=scalg.lu(A)

In [768]:
print(L)

[[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]


In [769]:
print(U)

[[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]


In [770]:
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [771]:
y=np.linalg.solve(L,B)
print(y)

[[1.        ]
 [5.25      ]
 [3.27272727]]


In [772]:
x3=np.linalg.solve(U,y)
print(x3)

[[ 3.4]
 [-3. ]
 [ 3.6]]


In [773]:
#alternativa de solucion 2
LU=scalg.lu_factor(A)
print(LU)

(array([[ 4.        ,  3.        , -1.        ],
       [ 0.75      ,  2.75      ,  3.75      ],
       [ 0.25      ,  0.09090909,  0.90909091]]), array([1, 2, 2], dtype=int32))


In [774]:
x=scalg.lu_solve(LU,B)
print('x:',x)

x: [[ 1. ]
 [ 0.5]
 [-0.5]]


## Cholesky

Si A es simétrica y definida positiva.

In [775]:
print(A)

[[ 1.  1.  1.]
 [ 4.  3. -1.]
 [ 3.  5.  3.]]


In [776]:
#chequeo de positiva definida
d1=scalg.det([[1]])
d2=scalg.det([[1.,1.],[4.,3.]])
d3=scalg.det(A)
print('chequeo positiva definida')
print('d1:',d1)
print('d2:',d2)
print('d3:',d3)

chequeo positiva definida
d1: 1.0
d2: -1.0
d3: 10.0


### otro ejemplo para probar Cholesky 

In [777]:

A=np.array([[4,2,14],[2,17,-5],[14,-5,83]])

B=np.array([[14],[-101],[155]])

In [778]:
L=scalg.cholesky(A,lower=True)
U=scalg.cholesky(A,lower=False)

print('Matriz A:\n',A)
print('L Cholesky:\n',L)
print('U Cholesky:\n',U)

Matriz A:
 [[ 4  2 14]
 [ 2 17 -5]
 [14 -5 83]]
L Cholesky:
 [[ 2.  0.  0.]
 [ 1.  4.  0.]
 [ 7. -3.  5.]]
U Cholesky:
 [[ 2.  1.  7.]
 [ 0.  4. -3.]
 [ 0.  0.  5.]]


In [779]:
#Solucion de dos sistemas triangulares
y=scalg.solve(L,B)
x=scalg.solve(U,y)

print('Solucion Cholesky:\n',x)

Solucion Cholesky:
 [[ 3.]
 [-6.]
 [ 1.]]


In [780]:
#verificacion
x=scalg.solve(A,B)
print(x)

[[ 3.]
 [-6.]
 [ 1.]]


# Métodos Iterativos: Jacobi y Gauss-Seidel

In [781]:
import numpy as np
A=np.array([[4.,-1.,2.],[2.,5.,1.],[1.,1.,-3.]])

B=np.array([[-12.],[5.],[-4.]])

In [782]:
print(A)

[[ 4. -1.  2.]
 [ 2.  5.  1.]
 [ 1.  1. -3.]]


In [783]:
np.diag(A)

array([ 4.,  5., -3.])

In [784]:
D=np.diag(np.diag(A))
print(D)

[[ 4.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0. -3.]]


In [785]:
L=np.tril(A,k=-1)
print(L)    

[[0. 0. 0.]
 [2. 0. 0.]
 [1. 1. 0.]]


In [786]:
U=np.triu(A,k=1)
print(U)

[[ 0. -1.  2.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [787]:
#Metodo de Jacobi - forma matricial
iter=0
tolerancia=1e-3 #equivale a 0.001
error=1.0

xold=np.array([[0.],[0.],[0.]])

n=len(B) #calcula el tamaño vector B
xnew=np.zeros(n)

while error>=tolerancia:
    cj=np.matmul(-np.linalg.inv(D),(L+U))
        
    dj=np.matmul(np.linalg.inv(D),B)
        
    xnew=np.matmul(cj,xold)+dj
        
    error=np.linalg.norm(xnew-xold,2) #error con la norma euclidea
        
    iter+=1
        
    xold=xnew   #actualizando el xold

In [788]:
print('Programa metodo Jacobi de manera matricial AX=B')
print('+++++++++++++++++++++')

print('Matriz A:\n',A)
print('Matriz B:\n',B)

print('tolerancia:',tol)

print('+++++++++++++++++++++')
print('solucion:\n',xnew)

print('Numero iteraciones:',iter)

Programa metodo Jacobi de manera matricial AX=B
+++++++++++++++++++++
Matriz A:
 [[ 4. -1.  2.]
 [ 2.  5.  1.]
 [ 1.  1. -3.]]
Matriz B:
 [[-12.]
 [  5.]
 [ -4.]]
tolerancia: 0.001
+++++++++++++++++++++
solucion:
 [[-3.00016239]
 [ 1.99972205]
 [ 1.00018563]]
Numero iteraciones: 16


In [789]:
print(error)

0.0007695239271969423


In [790]:
print(tolerancia)

0.001
