# Solucion de sistemas de ecuaciones lineales

## Metodos directos

In [56]:
import numpy as np
import scipy.linalg as scy

In [57]:
A=np.array([[2,4,6],[4,5,6],[3,1,-2]])
print(A)

[[ 2  4  6]
 [ 4  5  6]
 [ 3  1 -2]]


In [58]:
B=np.array([[18],[24],[4]])
print(B)

[[18]
 [24]
 [ 4]]


## Determinante de una matriz

In [59]:
determinanteA=np.linalg.det(A)
print(determinanteA)

5.999999999999997


## Inversa

In [60]:
inversaA=np.linalg.inv(A)
print(inversaA)

[[-2.66666667  2.33333333 -1.        ]
 [ 4.33333333 -3.66666667  2.        ]
 [-1.83333333  1.66666667 -1.        ]]


## Solucion del sistema AX=B opcion 1

In [61]:
x=np.matmul(inversaA,B)
print(x)

[[ 4.]
 [-2.]
 [ 3.]]


## Solucion del sistema AX=B opcion 2

In [62]:
x=np.dot(inversaA,B)
print(x)

[[ 4.]
 [-2.]
 [ 3.]]


## Producto matriz por escalar

In [63]:
alpha=2
alpha*A

array([[ 4,  8, 12],
       [ 8, 10, 12],
       [ 6,  2, -4]])

## Diagonal de una matriz

In [64]:
diagonal=np.diag(np.diag(A))
print(diagonal)

[[ 2  0  0]
 [ 0  5  0]
 [ 0  0 -2]]


In [65]:
diagonal=np.diag(A,k=1) #la k te dice que numero de diagonal coger np.gsus(A)
print(diagonal)

[4 6]


In [66]:
diagonal=np.diag(A,k=-1)
print(diagonal)

[4 1]


## Triangular

In [67]:
np.triu(A)

array([[ 2,  4,  6],
       [ 0,  5,  6],
       [ 0,  0, -2]])

In [68]:
np.tril(A)

array([[ 2,  0,  0],
       [ 4,  5,  0],
       [ 3,  1, -2]])

## Matrices aleatorias

In [70]:
AA=np.random.rand(5,5)*10
print(AA)

[[2.29709084 2.34267417 5.10731146 2.76831788 6.98264892]
 [0.69288814 1.19489183 5.11193355 6.81333678 1.15557256]
 [6.34541175 9.31931911 4.60929163 9.10976679 7.65888129]
 [8.85319352 6.00774374 3.86808639 3.00618704 8.82434925]
 [2.76647324 0.46641199 4.61996198 0.9175101  6.08729586]]
