## LU Decomposition

In [41]:
import numpy as np
import scipy.linalg as scy

In [42]:
A=np.array([[2,4,6],[4,5,6],[3,1,-2]])
B=np.array([[18],[24],[4]])
P,L,U=scy.lu(A)

In [43]:
print(P)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [44]:
print(L)

[[ 1.          0.          0.        ]
 [ 0.75        1.          0.        ]
 [ 0.5        -0.54545455  1.        ]]


In [45]:
print(U)

[[ 4.          5.          6.        ]
 [ 0.         -2.75       -6.5       ]
 [ 0.          0.         -0.54545455]]


In [46]:
y=np.linalg.solve(L,B)
print(y)

[[18.        ]
 [10.5       ]
 [ 0.72727273]]


In [47]:
x=np.linalg.solve(U,y)
print(x)

[[ 7.33333333]
 [-0.66666667]
 [-1.33333333]]
